project/articles/views.py
# imports

from flask import render_template, Blueprint, send_from_directory
from flask import request, redirect, url_for, flash
from werkzeug.utils import secure_filename
from project import db
from project.models import Article
from .forms import AddArticleForm, AddTextandArticle, AddTextforCreative, SumyForm, AddVideoCreationForm
import nltk
from nltk import tokenize
from datetime import datetime, date
import random, os
from PIL import Image
# import python files
from . import add_article_python
from . import text_summ__word_freq_algo, textsumm_gensim_textrank_algo
from . import textsumm_sumy_algorithm
from project import app
from . import post_to_social_media
from . import generate_media
from . import create_video
from . import create_video_crux_style

# congfig 
articles_blueprint = Blueprint('articles', __name__, template_folder = 'templates')
UPLOAD_FOLDER = '/path/to/the/uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
APP_ROOT = os.path.dirname(os.path.abspath(__file__))   # gives path till articles folder
images_directory = os.path.join(app.config['UPLOAD_FOLDER'], 'images')
thumbnails_directory = os.path.join(app.config['UPLOAD_FOLDER'], 'thumbnails')
if not os.path.isdir(images_directory):
    os.mkdir(images_directory)
if not os.path.isdir(thumbnails_directory):
    os.mkdir(thumbnails_directory)
    
############################################    

@articles_blueprint.route('/', methods=['GET', 'POST'])
def index(keywords = "empty"):
    
    return render_template('index.html', keywords = keywords)

@articles_blueprint.route('/check_db', methods = ['GET','POST'])
def get_data_db():
    all_articles = Article.query.all()
    print(Article.query.all())
    print("-------2-----------")
    
    return render_template('get_data_db.html', articles = all_articles)


@articles_blueprint.route('/live_site', methods = ['GET'])
def get_live_site():
    return render_template('statsmatter_live_page.html')


@articles_blueprint.route('/add/', methods = ['GET','POST'])    


#################### Random Sentence Picker ##############################

def random_sentence_picker_algo():       

    # form = AddArticleForm(int(request.form['final_sentence_count']),request.form['article_content']    

    if request.method == 'POST':
                
        form = AddArticleForm(request.form)
        print("---------add----------")
        print(request.form['final_sentence_count'])
        print(form.validate_on_submit())
        if form.validate_on_submit():                        
            add_article_python.add_article_logic(form)
            
        else:
            print("---------add else----------")
            flash('ERROR! Article was not added.', 'error')
    
    return render_template('add_article.html')



###################### For Sumy Lex Rank Algorithm #######################

@articles_blueprint.route('/sumy_lex_rank', methods = ['GET', 'POST'])

def sumy_lex_rank_method(keywords = "", summary = "" ):

    keywords = ""
    if request.method == 'POST':         

        #  form = SumyForm(request.form)
        print("-------sumy---------")
        print(request.form)
        keywords = ""
        # Validate the form
        form = SumyForm(request.form)
        print(form.final_sentence_count.data)
        if form.validate_on_submit():  

            summary = textsumm_sumy_algorithm.textsumm_sumy_algorithm_method(form)

            print(summary)
        if form.errors:
            for error_field, error_message in form.errors.items():
                flash("Field : {field}; error : {error}".format(field=error_field, error=error_message))
        
    else:
        print("problem with the post method")

    return render_template('index.html',keywords = keywords, summary = summary) 


############ For Word Frequency Algorithm ######################

@articles_blueprint.route('/add_word_freq', methods = ['GET','POST'])    
            
def nlp_word_freq():        
    if request.method == 'POST':
        # show generates output images

        form = AddArticleForm(request.form)
        print(request.form)
        print(type(request.form['article_content']))
        
        if form.validate_on_submit():                        
            path_to_img_to_upload = text_summ__word_freq_algo.word_freq_method(form)
            print("view ---------")
            path_to_img_to_upload =  "/static/images/output/image_output.png"
            print(path_to_img_to_upload)
        else:
            flash_errors(form)
            flash('ERROR! Article was not added.', 'error')
    
    else:   
        # show default background
        path_to_img_to_upload = "/static/images/darpnai_twitter_background.png"
    
    # path_to_img_to_upload = os.path.join(app.config['UPLOAD_FOLDER'], 'images/output/image_output.png')

    return render_template('nlp_word_freq_2.html', path_to_img_to_upload = path_to_img_to_upload )    


############### Gensim Algorithm ########################

@articles_blueprint.route('/add_genism', methods = ['GET','POST']) 

def text_summ__textrank_gensim():

    error = None
    # default data to be returned
    keywords = ""
    summary = ""
    path_to_img_to_upload = "/static/images/darpnai_twitter_background.png"

    if request.method == 'POST':

        form = AddTextandArticle(request.form)
        print(form)
        print("------Gensim testing-------")                
        
        if form.validate_on_submit():                        
            # path_to_img_to_upload = text_summ__word_freq_algo.word_freq_method(form)
            print("view ---------")
            try:
                #pushing the data to the database
                url = "https://www.statsmatter.in"
                heading =  "This is a demo heading" + str(form.ratio.data )
                content = form.articletext.data 

                # db data to push
                article = Article( date.today() ,datetime.now(),url,heading ,content, False)

                # db.session.add(article1)
                db.session.add(article)
                # commit the changes
                db.session.commit()
            except Exception as e:
                print(e)
                print("error adding to database")
                flash("Data not added to database")
            else:
                print("Successfully added to database") 
                flash("Successfully added to database")               

            keywords = ""
            (keywords, summary) = textsumm_gensim_textrank_algo.gensim_textrank_method(form)
            
            path_to_img_to_upload =  "/static/images/output/image_output.png"
            
        else:
            # 
            print("---Data not validated---")

    
    
    # path_to_img_to_upload = os.path.join(app.config['UPLOAD_FOLDER'], 'images/output/image_output.png')

    return render_template('index.html', keywords = keywords, summary = summary, error = error)

################ Posting creative to Social Media #################################

@articles_blueprint.route('/post_to_sm', methods = ['GET','POST'])   

def post_creative_to_social_media(path_to_img_to_upload = "/static/images/output/image_output.png"):

    '''
        picking generated image and posting it to the twitter and other social media
        input : path to input image
        output : nothing
    '''    
    path_to_generated_image = os.path.join(app.config['UPLOAD_FOLDER'], 'images/output/image_output.png')
    
    
    if request.method == 'POST':  
        print("---------request-----")  
        print(request.form)
        if request.form['post_sm'] == "yes_twitter":
            print(request.form['post_sm'])
            twitter_status = request.form['twitterstats']
            post_to_social_media.post_to_twitter(path_to_generated_image, twitter_status)
            print("-----post_to_creative-------")
            # image to be uploaded to html
            path_to_img_to_upload = "/static/images/output/image_output.png"
        elif request.form['post_sm'] == "yes_insta":
                  
            instagram_status = request.form['twitterstats']
            post_to_social_media.post_to_instagram(path_to_generated_image, instagram_status)
            # path_to_img_to_upload = "/static/images/darpnai_twitter_background.png"
            path_to_img_to_upload = "/static/images/output/image_output.png"
    else:
        redirect(url_for('articles.nlp_word_freq'))
    
    return render_template('result.html', path_to_img_to_upload = path_to_img_to_upload )

############## Final Result html #########################

@articles_blueprint.route('/result/', methods = ['GET','POST'])   

def result():
    # default value
    keywords = ""
    summary = ""
    if request.method == 'POST':        
        print("-----result-------")
        form = AddTextforCreative(request.form)
        summary = request.form['summaryText'] 
        keywords = request.form['twitterHashtags']
        path_to_img_to_upload = generate_media.generate_image_with_background(summary) 
        print(path_to_img_to_upload)
    else:
        print("-----no result-------")
    # keywords = request.form['summaryText'] 
    
    print(keywords)
    
    path_to_img_to_upload = "/static/images/output/image_output.jpg"
    return render_template('result.html',keywords = keywords,  path_to_img_to_upload = path_to_img_to_upload)


############## Get Video content #########################

@articles_blueprint.route('/get_video', methods = ['GET','POST'])   

def generate_video():        

    if request.method == 'POST': 

        print("---------generate video ------------")
        print("Generate Video Post Method is Working")
        form = AddVideoCreationForm(request.form)
        
        if form.validate_on_submit():
            print("Form is validated!")                        
            # create_video.create_video_auto_generated_images(form)

project/articles/templates/_form_macros.html
{% macro render_field(field) %}
 
 
<dt>{{ field.label }}:
 
<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>
 
 
{% endmacro %}

project/articles/templates/error.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Error!!!</h1>
        <p>{{ message }}</p>
    </div>
</div>
{% endblock %}

project/articles/templates/forms.html
<!-- form for Gensim algorithm -->

<form role="form" id="formGensim" method='POST' action='{{ url_for('articles.text_summ__textrank_gensim') }}'>
    
    <div class="form-group">

        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

        <div class="form-group row">
            <h3>Form for Gensim Algo</h3>
        </div>
        <div class="form-group row">
            <label for="article-url-input" class="col-2 col-form-label">URL</label>
            <div class="col-10">
                <input class="form-control" type="url" value="" id="article-url-input" name="articleurl"
                    placeholder="Provide dummy URL">
            </div>
        </div>

        <div class="form-group row shadow-textarea">
            <label for="exampleFormControlTextarea6">Or Enter the text</label>
            <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" name="articletext" rows="3"
                placeholder="Write something here..."></textarea>
        </div>

        <div class="form-group row">
            <label for="example-number-input" class="col-2 col-form-label">Number</label>
            <div class="col-10">
                <input class="form-control" type="number" step=".01" id="example-number-input" name="ratio">
            </div>
        </div>

    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <br>


</form>

<!-- form for Random method -->


<form role="form" class="hidden" id="formRand" method='POST' action='{{ url_for('articles.random_sentence_picker_algo') }}'>
    
    <div class="form-group">

        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

        <div class="form-group row">
            <h3>Form for Random Algo</h3>
        </div>

        <div class="form-group row">
            <label for="article-url-input" class="col-2 col-form-label">URL</label>
            <div class="col-10">
                <input class="form-control" type="url" value="" id="article-url-input" name="articleurl"
                    placeholder="Provide dummy URL">
            </div>
        </div>

        <div class="form-group row shadow-textarea">
            <label for="exampleFormControlTextarea6">Or Enter the text</label>
            <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" name="articletext" rows="3"
                placeholder="Write something here..."></textarea>
        </div>

        <div class="form-group row">
            <label for="example-number-input" class="col-2 col-form-label">Choose number of sentences :</label>
            <div class="col-10">
                <input class="form-control" type="number" id="example-number-input" name="ratio">
            </div>
        </div>

    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <br>


</form>


<form role="form" id="formWfreq" method='POST' action='{{ url_for('articles.text_summ__textrank_gensim') }}'>
    
    <div class="form-group">

        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

        <div class="form-group row">
            <h3>Form for WordFreq Algo</h3>
        </div>

        <div class="form-group row">
            <label for="article-url-input" class="col-2 col-form-label">URL</label>
            <div class="col-10">
                <input class="form-control" type="url" value="" id="article-url-input" name="articleurl"
                    placeholder="Provide dummy URL">
            </div>
        </div>

        <div class="form-group row shadow-textarea">
            <label for="exampleFormControlTextarea6">Or Enter the text</label>
            <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" name="articletext" rows="3"
                placeholder="Write something here..."></textarea>
        </div>

        <div class="form-group row">
            <label for="example-number-input" class="col-2 col-form-label">Choose number of sentences :</label>
            <div class="col-10">
                <input class="form-control" type="number" step=".01" id="example-number-input" name="ratio">
            </div>
        </div>

    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <br>


</form>


<!-- form for Sumy Lexrank method -->


<form role="form" id="formSumyLexRank" method='POST' action='{{ url_for('articles.sumy_lex_rank_method') }}'>
    
    <div class="form-group">

        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

        <div class="form-group row">
            <h3>Form for Sumy LexRank Algoritm</h3>
        </div>

        <div class="form-group row">
            <label for="article-url-input" class="col-2 col-form-label">URL</label>
            <div class="col-10">
                <input class="form-control" type="url" value="" id="article-url-input" name="articleurl"
                    placeholder="Provide dummy URL">
            </div>
        </div>

        <div class="form-group row shadow-textarea">
            <label for="exampleFormControlTextarea6">Or Enter the text</label>
            <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" name="articletext" rows="3"
                placeholder="Write something here..."></textarea>
        </div>

        <div class="form-group row">
            <label for="example-number-input" class="col-2 col-form-label">Choose number of sentences :</label>
            <div class="col-10">
                <input class="form-control" type="number" id="example-number-input" name="final_sentence_count">
            </div>
        </div>

    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <br>


</form>

project/articles/templates/gallery.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
  <div class="row">
      <h1>Gallery</h1>            
  </div>
  {% if thumbnail_names %}
    <div class="row">
      {% for thumbnail_name in thumbnail_names %}
      <div class="col-xs-6 col-md-3 img-div">
           
          <img src="{{url_for('articles.thumbnails', filename=thumbnail_name)}}" class="img-responsive thumb" data-toggle="modal" data-target="#image{{ loop.index0 }}" />
          <div class="modal fade" id="image{{ loop.index0 }}" tabindex="-1" role="dialog" aria-labelledby="image{{ loop.index0 }}ModalLabel">
              <div class="modal-dialog modal-lg">
                  <div class="modal-content">                    
                      <img src="{{url_for('articles.images', filename=thumbnail_name)}}" class="img-responsive" />
                  </div>
              </div>
          </div>
      </div>
      {% endfor %}
    </div>
  {% endif %}
</div>
{% endblock %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{url_for('static_files', filename='gallery.css')}}">
{% endblock %}

project/articles/templates/gensim_nlp.html
{% extends "layout.html" %}

{% block content %}
<div class="add-article">

  <div class="page-header">
    <!-- <h2>NLP - Text Summarization</h2> -->
    <h3> Text Summarization with Gensim ( TextRank )</h3>
  </div>

  <div class="container">
    <div class="row">

      <div class="col-lg-5" show-form">
        <div class="form-group row">
          <h4>Add a New article </h4>
        </div>

        <form role="form" method='POST' action='{{ url_for('articles.text_summ__textrank_gensim') }}'>

          <div class="form-group">

            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <div class="form-group row">
              <label for="example-date-input" class="col-2 col-form-label">Date</label>
              <div class="col-10">
                <input class="form-control" type="date" value="2019-10-29" id="example-date-input" name="date">
              </div>
            </div>

            <div class="form-group row">
              <label for="example-number-input" class="col-2 col-form-label">Number</label>
              <div class="col-10">
                <input class="form-control" type="number" step=".01" id="example-number-input" name="ratio">
              </div>
            </div>
            <div class="form-group row">
              <label for="text-input-choice" class="col-2 col-form-label">Type of Input</label>
              <br>
              <input type="radio" name="t_offset" value="yes" checked> It is a URL<br>
              <input type="radio" name="t_offset" value="no"> It is a Text File<br>
            </div>
            <div class="form-group row">
              <label for="article-url-input" class="col-2 col-form-label">URL</label>
              <div class="col-10">
                <input class="form-control" type="url" value="" id="article-url-input" name="articleurl"
                  placeholder="Provide dummy URL">
              </div>
            </div>

            <div class="form-group row shadow-textarea">
              <label for="exampleFormControlTextarea6">Or Enter the text</label>
              <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" name="articletext" rows="3"
                placeholder="Write something here..."></textarea>
            </div>
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
          <br>
          

        </form>

        {% for error in errors %}
        <h4>{{ error }}</h4>
        {% endfor %}
      </div>

      <div class="col-lg-5 show-image">

        <h2> KeyWords in Article</h2>
        {{ keywords}}
        <h2> Summary </h2>
        {{ summary }}
        <br>
        <a href="{{ url_for('articles.result', keywords = keywords, summary = summary) }}" class="btn btn-info" role="button">Get the Creative</a>
      </div>

    </div>
  </div>



</div>

{% endblock %}

project/articles/templates/index.html
{% extends "layout.html" %}



{% block content %}

<div class="jumbotron text-center" style="color:blue;background-image: url(); background-size: 100% 100%;">

  <h2> <b>StatsMatter</b> - An AI Magazine for AI related News, created by AI !</h2>
  <p> Artificial Intelligence in NLP - Developed by <b>Vipul Pandey</b></p>

</div>

<h1 style="color:green;text-align:center;">
  Trending AI News Summarizer
</h1>




<div class="container">


  <div class="row">

    <div class="col-md-5" show-form">

      <div class="form-group row">
        <h3>Choose Algorithm for News Graphic</h3>
        <p>You will get the summary that can be edited, according to the algorithm</p>
        <div class="btn-group">
          <button type="button" name="algo" id="opSumy" onclick="insert1()" class="btn btn-default">Sumy
            LexRank</button>
          <button type="button" name="algo" id="opWfreq" onclick="insert2()" class="btn btn-primary">Word -
            Frequency</button>
          <button type="button" name="algo" id="opGensim" form="form1" class="btn btn-default">Gensim -
            TextRank</button>
          <br>
          <button type="button" name="algo" id="opDl" class="btn btn-primary">LSTM - Deep Learning</button>
        </div>
      </div>


      <div class="row">


        <!-- Recieves the error message -->
        {% with messages = get_flashed_messages() %}

          {% if messages %}
            {% for message in messages %}            
              <p><strong>Alert:</strong> {{ message }}
            {% endfor %}
            {% endif %}
          {% endwith %}

      </div>
      <div id="log"></div>


      {% include 'forms.html' %}



    </div>

    <!-- Providing Gap between grids -->
    <div class="col-md-1 show-image">

    </div>

    <div class="col-md-5 show-image">


      <h3> Summary ( You can edit here !)</h3>

      <form role="form" target="_blank" method='POST' action='{{ url_for('articles.result') }}'>

        <div class="form-group">

          <div class="form-group row">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <label for="exampleFormControlTextarea1">Method Used : </label>
            <textarea class="form-control rounded-0" name="summaryText" id="exampleFormControlTextarea1"
              rows="10">{{ summary }}</textarea>

            <h4> KeyWords in Article</h4>
            {{ keywords}}

            <h3>Hashtags for Social Media</h3>
            <textarea class="form-control" name="twitterHashtags" rows="3"
              placeholder="you can add hashtags..."> #Artificialintelligence #AI #Media  </textarea>
          </div>


        </div>
        <br>
        <button type="submit" class="btn btn-info">Get the creative</button>
        <!-- <button type="submit" class="btn btn-info">Get the creative</button> -->
      </form>


    </div>

  </div>


  <!-- Providing Gap between grids -->
  <div class="row top-buffer">

  </div>
  <!-- Progress Bar -->
  <div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
      aria-valuemax="100"></div>
  </div>



</div>



{% endblock %}

project/articles/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Text Summarization App">
  <meta name="author" content="Vipul Pandey">
  <title>NLP Text Summarization</title>
  <!-- styles -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>

  <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target="#recipes-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('articles.index') }}">NLP Graphic Creator</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{url_for('articles.generate_video')}}">NLP Video Creator</a></li>
          <li><a href="{{url_for('articles.nlp_word_freq')}}">NLP-WordFreq-ExtSumm</a></li>
          <li><a href="{{url_for('articles.result')}}">Final Contents</a></li>
          <li><a href="{{url_for('articles.get_live_site')}}">Check Live Site</a></li>
          <li><a href="{{ url_for('articles.get_data_db') }}">Check Database</a></li>

        </ul>
        <!-- <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Welcome!</a></li>
          </ul> -->
      </div>
      <!--/.nav-collapse -->
    </div><!-- /.container -->
  </nav>


  <div class="container">
    <div class="content">

      <!-- child template -->
      {% block content %}
      {% endblock %}

    </div>
    <div class="footer">
      <hr>
      <p>@ Vipul Pandey - 2019</p>
    </div>
  </div><!-- /.container -->

  <!-- scripts -->
  <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
    integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
    crossorigin="anonymous"></script>
  <script type=text/javascript src="{{url_for('static', filename='js/script.js') }}">
        </script>
  <!-- <script>
    // ...

    // By default forms are hidden

    $("#formSumyLexRank").hide();
    $("#formWfreq").hide();
    $("#formGensim").hide();
    // $("#formDl").hide();

    $('body').click(function (event) {

      var log = $('#log');

      if ($(event.target).is('#opSumy')) {
        log.html(event.target.id + ' was clicked.');
        $("#formSumyLexRank").show();

        // hide the other forms
        $("#formWfreq").hide();
        $("#formGensim").hide();

      } else if ($(event.target).is('#opWfreq')) {
        log.html(event.target.id + ' was clicked.');
        $("#formWfreq").show();

        // hide the other forms
        $("#formSumyLexRank").hide();
        $("#formGensim").hide();

      } else if ($(event.target).is('#opGensim')) {
        log.html(event.target.id + ' was clicked.');
        $("#formGensim").show();
        // hide the other forms
        $("#formSumyLexRank").hide();
        $("#formWfreq").hide();

      } else if ($(event.target).is('#opDl')) {
        log.html(event.target.id + ' was clicked.');
      } else {
        log.html('');
      }
    });
  </script> -->


</body>

</html>

project/articles/templates/nlp_word_freq_2.html
{% extends "layout.html" %}

{% block content %}
<div class="add-article">

  <div class="page-header">
    <!-- <h2>NLP - Text Summarization</h2> -->
    <br>
    <h3> Word - Freq Algorithm ( using signal in the sentences !! )</h3>
  </div>

  <div class="container">
    <div class="row">

      <div class="col-lg-5" show-form">
        <h4>Add a New article </h4>
        <form role="form" method='POST' action='{{ url_for('articles.nlp_word_freq') }}'>

          <div class="form-group">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type="number" name="final_sentence_count" class="form-control" id="num-box"
              placeholder="Final sentence count..." style="max-width: 300px;" autofocus required>
            <input type="text" name="article_content" class="form-control" id="content-box"
              placeholder="Enter the content..." style="max-width: 500px;" autofocus required>
            <!-- <br>
            <label for="entertwitterstatus">Enter the text !!</label>
            <textarea class="form-control" id="textinput" name="article_content" rows="3" placeholder="you can add hashtags...">  </textarea> -->
            <h5>Show summary</h5>
            <input type="radio" name="twitter_offset" value="yes" checked> Yes<br>            
            <input type="radio" name="twitter_offset" value="no"> No<br>
            <!-- <a href=”/your_flask_funtion”><input type=”button” value=”call_flask_funtion”></a> -->
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
          
        </form>        

        {% for error in errors %}
        <h4>{{ error }}</h4>
        {% endfor %}
      </div>

      <div class="col-lg-5 show-image">
          <img class="img-responsive rounded head-img" src="{{ path_to_img_to_upload }}" alt="Image Failed to Load">

          <form role="form" method='POST' action='{{ url_for('articles.post_creative_to_social_media') }}'>
            <div class="hover-buttons">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
              <br>
              
              <label for="entertwitterstatus">Enter Twitter status</label>
              <textarea class="form-control" name="twitterstats" rows="3" placeholder="you can add hashtags..."> #artificialintelligence #aitraining #nlp  </textarea>
              <br>
              <button type="submit" name = "post_sm" class="btn btn-danger btn-sm" value="yes_twitter">Post to twitter </button>
              <button type="submit" name = "post_sm" class="btn btn-danger btn-sm" value="yes_insta">Post to instagram</button>
              
            </div>            
          </form>
        </div>
      
    </div>
  </div>



</div>

{% endblock %}

project/articles/templates/result.html
{% extends "layout.html" %}

{% block content %}

<div class="row">
  <div class="col-md-8 show-image">


    <h3 class="display-4">Final Creative Before Posting</h3>
    <img class="img-responsive rounded head-img" width=100%
      src="{{url_for('static',filename = 'images/output/image_output.png')}}" alt="Image Failed to Load">

  </div>

  <div class="col-md-4 show-hashtag">
    <h3>{{ keywords }}</h3>
    <form role="form" method='POST' action='{{ url_for('articles.post_creative_to_social_media') }}'>
      <div class="hover-buttons">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <br>

        <label for="entertwitterstatus">Enter Twitter status</label>
        <textarea class="form-control" name="twitterstats" rows="3"
          placeholder="you can add hashtags..."> #Artificialintelligence #AI #Media  </textarea>
        <br>
        <button type="submit" name="post_sm" class="btn btn-danger btn-sm" value="yes_twitter">Post to twitter
        </button>
        <button type="submit" name="post_sm" class="btn btn-danger btn-sm" value="yes_insta">Post to
          instagram</button>
      </div>
    </form>
  </div>

</div>

{% endblock %}